name: resource_network_fetcher
description: Uses the NetworkBoundResources to control the offline-first or only to centralize the errors from fetching from the network or any other function.
version: 1.1.2
homepage: https://polazzo.dev/
repository: https://github.com/LucazzP/resource_network_fetcher
issue_tracker: https://github.com/LucazzP/resource_network_fetcher/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
